services:
  redis:
    image: redis
    volumes:
      - redis_volume:/var/lib/redis/data
    ports: ["6379"]
    networks:
      - back-tier

  voting-app:
    image: voting-app
    build: ./vote
    command: python app.py
    depends_on:
      - redis
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  postgres:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db_volume:/var/lib/postgresql/data"
    networks:
      - back-tier

  result-app:
    image: result-app
    build: ./result
    command: nodemon server.js
    depends_on:
      - postgres 
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker-app:
    image: worker-app
    build:
      context: ./worker
    depends_on:
      - redis
      - postgres
    networks:
      - back-tier

volumes:
  redis_volume:
  db_volume:

networks:
  front-tier:
  back-tier:
